### PR TITLE
Added custom method to filter urls

### PR DESCRIPTION
**Pull request by Mte90**
This patch eanble with a custom function in `config.php` to clean up the url from parameters:

```
    'profiler.clean_url' => function($uri) {
        $uri = str_replace('?enable-tideways', '', $uri);
        $uri = str_replace('%3Fenable-tideways', '', $uri);
        return $uri;
    }
```

### CODE REVIEW

**Comment by glensc** [comment]
you are modifying the `$uri`, how it's related to validating?

also, do not add a global symbol. add config key with closure as a value, like `'profiler.enable'` already exists. pay attention to backward compatibility.

**Comment by Mte90** [comment]
Yes validating is not the better term, maybe is better like `clean_url`.
I am not sure how to pass a callback from the config and execute it inside the project and I saw that the function was the most easy way.
Do you have any hints for it?

**Comment by glensc** [comment]
I gave you the hint. search that string through this project.

**Comment by Mte90** [comment]
Looking at https://github.com/perftools/xhgui-collector/search?q=profiler.enable&unscoped_q=profiler.enable the project is using the callback without sending to them any parameters.
I already looked in the code but an example for my needs to check there wasn't, this was also one of the reason of a custom function.

**Comment by glensc** [comment]
so, add the parameter you need... 

- https://www.php.net/manual/en/functions.anonymous.php

**Comment by Mte90** [comment]
rewritten as anonymous function in the config array, let me know if now is good :-)

**Comment by glensc** [comment]
the change is ok, but it should be somehow documented, perhaps add a working example to default config (return `$url` itself)

but looking at current defaults, how is your filter different from `'profiler.simple_url'`:
- https://github.com/perftools/xhgui-collector/blob/726adf84210aa0a232d8471033ab0b9d0a04121a/config/config.default.php#L55

**Comment by lauripiisang** [comment]
I think the point here is to ensure that no sensitive data is saved and have control over how the replacements are done, e.g. ?api_token=1abc325&do_thing=thing1 -> ?api_token=XXXXXX&do_thing=thing1 . 
`simple_url` adds a property, but `$url` still gets saved - https://github.com/perftools/xhgui-collector/pull/24/files#diff-3737a2b54402ad429752791444589b15R173

**Comment by lauripiisang** [comment]
add documentation about this property into [the default config](https://github.com/perftools/xhgui-collector/blob/726adf84210aa0a232d8471033ab0b9d0a04121a/config/config.default.php), then it can be merged. I'd call the property `replace_url` or `process_url`, as it's really more abstract than `clean`, but I don't have that strong of an opinion.

**Comment by Mte90** [comment]
I preferred a new function because on https://github.com/perftools/xhgui readme is explained that `simple_url` is used to remap better the urls or remove the pagination https://github.com/perftools/xhgui/blob/master/config/config.default.php#L55

**Review by lauripiisang — APPROVED** [review]

**Pull request merged**
