### PR TITLE
Revert "Flush output for fastcgi SAPI"

### LINKED ISSUE #19: Calling fastcgi_finish_request() during a shutdown function prevents subsequent shutdown functions from firing
In #13, a call to `fastcgi_finish_request()` was added inside the collector's shutdown function. This unfortunately prevents all subsequent shutdown functions from firing.

I don't fully know why this is the case, but I _do_ know that any shutdown function that `exit`s will cause subsequent ones to not trigger. This may be related.

The bug can be demonstrated by adding the following code anywhere in your PHP application and observing that it does not fire. If the call to `fastcgi_finish_request()` is removed, it fires as expected.

```php
{{{
register_shutdown_function( function() {
	var_dump( 'Nooooooooooooo' );
} );
```

cc @benbor

### PR DESCRIPTION
**Pull request by johnbillion**
Fixes #19.

This reverts commit 3c173f9615dd10fd4ae1c35d6d02b4d38ede651c.

### CODE REVIEW

**Comment by markstory** [comment]
Won't this just cause #13 to regress and leave fastcgi servers hanging until xhgui has submitted the profile data?

**Comment by johnbillion** [comment]
Yep. I'm not sure what other options we have, to be honest.

**Comment by benbor** [comment]
> Yep. I'm not sure what other options we have, to be honest.

I wonder do you read the [my comment](https://github.com/perftools/xhgui-collector/issues/19#issuecomment-461716751)  from #19 ? 
From my point of view the revert is not solution.

**Comment by lauripiisang** [comment]
resolved via #23

**Pull request closed without merging**
